// ═══════════════════════════════════════════════════════════════════════════════
// FORECAST ROBOT PLAY STYLES (spec §11) — how a simulated student decides what to
// forecast.
//
// ⚠ THE SEVEN STYLES ARE THE §2.3 BENCHMARK TABLE, WALKING. That is the whole design:
// spec §11 names exactly the rules spec §2.3 scores, so a robot cohort does not merely
// "fill the roster" — it reproduces the debrief slide. A demo instance populated by
// these robots yields a Tier-3 histogram whose spread lands ON the reference lines
// drawn beside it, and a class chart with a real gap between the average forecast and
// the systematic component. Elena can point at the chart and name what she is looking
// at, because the thing she is pointing at was generated by the rule she is naming.
//
//   naive             repeat last month           (§2.3: ~10,042)
//   seasonal-naive    same month last year        (§2.3:  ~4,180)
//   regression-fitter trend + one season dummy    (§2.3:    ~902)  ← the lecture's model
//   moving-average-12 the trap that looks clever  (§2.3:  ~9,029)
//   noise-chaser      over-reacts to the surprise (worse than naive, by construction)
//   anchored          flat at the history mean    (§2.3: ~37,840)
//   random-in-band    no policy at all
//
// ⚠⚠ EVERY STYLE DECIDES FROM WHAT IS ON THE STUDENT'S OWN SCREEN. The driver reads
// the demand series out of the rendered month-by-year grid — the same table a student
// reads — and passes it in. NOTHING here imports the server's model, and nothing knows
// a, b, H or σ. A robot that was handed the true process would make the cohort's chart
// say something false about what a student can achieve.
//
// ⚠ `regression-fitter` IS NOT A LEAK, for the same reason newsvendor's `optimizer` is
// not. It fits a least-squares trend plus a seasonal dummy to the sixty months in front
// of it, and it DISCOVERS which months are seasonal from the residuals rather than
// being told. That is precisely the exercise the assignment sets. It is reading the
// data, not the answer key.
// ═══════════════════════════════════════════════════════════════════════════════

/** Clamp to the forecast box's own bounds and round to a whole unit (spec §3). The
 *  server enforces the same range, so a style that drifted outside would be refused. */
export const legal = (v, p) =>
  Math.max(p.forecastMin, Math.min(p.forecastMax, Math.round(v)))

const monthOf = (period) => ((period - 1) % 12) + 1
const mean = (xs) => xs.reduce((a, b) => a + b, 0) / xs.length

/**
 * Least squares for y ~ [1, period] — a plain trend. Written out longhand rather than
 * imported: a robot that shared the server's arithmetic could not disagree with it, and
 * disagreeing is the only way this cohort would ever reveal a server-side bug.
 */
function fitTrend(points) {
  const n = points.length
  const sx = points.reduce((a, p) => a + p.period, 0)
  const sy = points.reduce((a, p) => a + p.demand, 0)
  const sxx = points.reduce((a, p) => a + p.period * p.period, 0)
  const sxy = points.reduce((a, p) => a + p.period * p.demand, 0)
  const denom = n * sxx - sx * sx
  if (Math.abs(denom) < 1e-9) return { intercept: sy / n, slope: 0 }
  const slope = (n * sxy - sx * sy) / denom
  return { intercept: (sy - slope * sx) / n, slope }
}

/**
 * The competent student's model: a trend, plus ONE indicator for the months that are
 * systematically high.
 *
 * ⚠ THE HIGH MONTHS ARE DISCOVERED, NOT SUPPLIED. Fit a plain trend, look at the mean
 * residual by calendar month, and call a month "high" when its mean residual is more
 * than half the largest. That is what a student does when they look at the grid and
 * notice November and December towering over everything — and it means the robot works
 * on an instance whose season an instructor has moved, exactly as a real student would.
 */
export function fitTrendPlusSeason(series) {
  if (series.length < 24) return null
  const plain = fitTrend(series)

  const residualByMonth = new Map()
  for (const p of series) {
    const r = p.demand - (plain.intercept + plain.slope * p.period)
    const m = monthOf(p.period)
    if (!residualByMonth.has(m)) residualByMonth.set(m, [])
    residualByMonth.get(m).push(r)
  }
  const meanResidual = new Map([...residualByMonth].map(([m, rs]) => [m, mean(rs)]))
  const biggest = Math.max(...meanResidual.values())
  if (!(biggest > 0)) return { predict: (period) => plain.intercept + plain.slope * period }

  const high = new Set([...meanResidual].filter(([, r]) => r > biggest / 2).map(([m]) => m))

  // Re-fit with the dummy in: regress demand on [1, period, isHigh] by solving the
  // 3×3 normal equations. Same longhand-on-purpose reasoning as above.
  const rows = series.map(p => [1, p.period, high.has(monthOf(p.period)) ? 1 : 0])
  const y = series.map(p => p.demand)
  const XtX = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
  const Xty = [0, 0, 0]
  rows.forEach((row, i) => {
    for (let j = 0; j < 3; j++) {
      Xty[j] += row[j] * y[i]
      for (let k = 0; k < 3; k++) XtX[j][k] += row[j] * row[k]
    }
  })
  const M = XtX.map((r, i) => [...r, Xty[i]])
  for (let c = 0; c < 3; c++) {
    let piv = c
    for (let r = c + 1; r < 3; r++) if (Math.abs(M[r][c]) > Math.abs(M[piv][c])) piv = r
    if (Math.abs(M[piv][c]) < 1e-9) {
      return { predict: (period) => plain.intercept + plain.slope * period }
    }
    const t = M[c]; M[c] = M[piv]; M[piv] = t
    for (let r = 0; r < 3; r++) {
      if (r === c) continue
      const f = M[r][c] / M[c][c]
      for (let k = c; k < 4; k++) M[r][k] -= f * M[c][k]
    }
  }
  const b = M.map((r, i) => r[3] / r[i])
  return {
    high,
    predict: (period) => b[0] + b[1] * period + b[2] * (high.has(monthOf(period)) ? 1 : 0),
  }
}

/** The demand at `period`, if this robot has seen it. */
const at = (series, period) => series.find(p => p.period === period)?.demand ?? null

export const STYLES = [
  {
    key: 'regression-fitter',
    label: 'Fits a trend plus a seasonal indicator — the lecture’s method',
    // The cohort's upper end, and the answer the assignment is teaching. See the file
    // header for why fitting is a calculation rather than a leak.
    decide: (p, series, period) => {
      const model = fitTrendPlusSeason(series)
      if (!model) return legal(mean(series.map(s => s.demand)), p)
      return legal(model.predict(period), p)
    },
    debrief: [
      'I put the five years into Excel and regressed demand on the month number plus an indicator for November and December. The trend came out around four units a month and the holiday lift around 230, so I forecast each month from that equation. I did not change the model as I went — there was no reason to.',
      'I noticed straight away that November and December towered over every other month in all five years, so I fitted a time trend with a single holiday dummy rather than twelve separate month effects. That gave me a formula I used for every month. My errors looked like noise rather than a pattern, which is what I was hoping for.',
    ],
  },
  {
    key: 'seasonal-naive',
    label: 'Forecasts the same month last year',
    decide: (p, series, period) => {
      const lastYear = at(series, period - 12)
      return legal(lastYear ?? mean(series.map(s => s.demand)), p)
    },
    debrief: [
      'I used the same month from the previous year as my forecast. It handled the December spike well, but the whole series was drifting upward and I was always a bit low because of it.',
      'My rule was simple: whatever this month was last year. That got the seasonal shape right, though it also carried over one year of randomness into every forecast.',
    ],
  },
  {
    key: 'naive',
    label: 'Repeats last month',
    decide: (p, series, period) => {
      const last = at(series, period - 1)
      return legal(last ?? mean(series.map(s => s.demand)), p)
    },
    debrief: [
      'I forecast each month at whatever the previous month came in at. It was easy but it clearly missed the seasonal jumps — I was badly wrong every November and again every January.',
      'I just repeated the last month. Looking at my results I was consistently a little low, which I now think was the upward trend I never accounted for.',
    ],
  },
  {
    key: 'moving-average-12',
    label: 'Averages the last twelve months — smooths the season away',
    // The trap that looks sophisticated (spec §2.3, point 2): averaging over a full
    // year deletes exactly the seasonality that carries the signal.
    decide: (p, series, period) => {
      const window = []
      for (let k = 1; k <= 12; k++) {
        const v = at(series, period - k)
        if (v !== null) window.push(v)
      }
      return legal(window.length > 0 ? mean(window) : mean(series.map(s => s.demand)), p)
    },
    debrief: [
      'I used a twelve-month moving average, which felt like the most rigorous thing available. In hindsight it flattened out the seasonality completely — my December forecasts were nowhere near December demand.',
      'I averaged the previous twelve months for each forecast to smooth out the noise. It smoothed out the pattern too, which I did not realise until I saw how badly the holiday months went.',
    ],
  },
  {
    key: 'noise-chaser',
    label: 'Over-reacts to the last surprise',
    // Spec §8's Q8, played: revising toward unsystematic variability makes MSE worse.
    decide: (p, series, period) => {
      const model = fitTrendPlusSeason(series)
      const base = model ? model.predict(period) : mean(series.map(s => s.demand))
      const last = at(series, period - 1)
      if (last === null || !model) return legal(base, p)
      // Over-correct by 1.4× the previous month's surprise — in the same direction.
      const surprise = last - model.predict(period - 1)
      return legal(base + 1.4 * surprise, p)
    },
    debrief: [
      'I had a rough model but I kept adjusting it after every month. If demand came in high I pushed the next forecast up, if it came in low I pulled it down. It felt responsive at the time; my errors got bigger rather than smaller.',
      'Every time I was surprised I changed my forecast to compensate. I was chasing the ups and downs and I think I ended up further from the truth than if I had left it alone.',
    ],
  },
  {
    key: 'anchored',
    label: 'Flat at the five-year average, never updates',
    // Spec §2.3's "simple forecast" — the lecture's starting point, and the worst rule
    // on the table by an order of magnitude.
    decide: (p, series) => legal(mean(series.slice(0, 60).map(s => s.demand)), p),
    debrief: [
      'I worked out the average of the five years of history and used that number every month. It seemed like the least risky choice. Seeing the results, it clearly ignored both the growth and the holiday season.',
      'I picked one number — the overall average — and stuck with it. That was simple but obviously wrong for December, and it got steadily worse as the series grew.',
    ],
  },
  {
    key: 'random-in-band',
    label: 'Guesses within the historical range',
    // Every class has one, and the noise is useful: it keeps the class-average line
    // from looking cleaner than a real cohort's, and it populates the histogram tail.
    decide: (p, series) => {
      const values = series.map(s => s.demand)
      const lo = Math.min(...values) * 0.8
      const hi = Math.max(...values) * 1.2
      return legal(lo + Math.random() * (hi - lo), p)
    },
    debrief: [
      'I did not really settle on a method. I looked at the range the data had covered and picked something inside it each month.',
      'Honestly I was guessing within the range I could see. Some months were close and some were not, and I never found a pattern I trusted.',
    ],
  },
]

/**
 * N robots, assigned round-robin over a SHUFFLED pool (spec §11).
 *
 * Shuffled so a four-student run is not always the first four styles in file order, and
 * round-robin so a fourteen-student run covers every style twice rather than picking
 * fourteen at random and leaving two behind. Both matter for the same reason: the
 * cohort exists to fill the §2.3 comparison, and a histogram missing its extremes is
 * not the test.
 */
export function assignStyles(n) {
  const shuffled = [...STYLES].sort(() => Math.random() - 0.5)
  return Array.from({ length: n }, (_, i) => shuffled[i % shuffled.length])
}
