// ═══════════════════════════════════════════════════════════════════════════════
// PROCUREMENT ROBOT PLAY STYLES — how a simulated student decides what to bid.
//
// ⚠⚠ THE STYLES ARE THE §9 SCATTER'S OWN AXES, WALKING. That is the design: a cohort
// populated by these robots produces a Tier-3 class chart with the shape Elena's lecture
// describes — a cluster ON the optimal line, a row of points ON the 45° line, and a
// visible band above it. She can point at the chart and name what she is looking at,
// because the thing she is pointing at was generated by the rule she is naming.
//
//   equilibrium     bids β(c) exactly            → sits ON the optimal line
//   cost-bidder     bids its own cost            → sits ON the 45° line, earns 0
//   over-marker     marks up far too much        → high band, rarely wins
//   under-marker    shaves below the optimum     → wins often, earns thin
//   random-in-band  no policy at all             → the noise a real class contains
//
// ⚠⚠ `loss-maker` IS GONE (Elena, 2026-08-04), and DELETED rather than left dead. It bid
// below its own cost to populate the region under the 45° line. **That region can no
// longer be populated by anybody**: no bidder in this auction may bid below their own
// cost, in either format, so `validateBid` refuses it at submit. A persona that exists to
// demonstrate a rejected move would produce a cohort of refused rounds, not a chart.
// Five styles, not six.
//
// ⚠⚠ EVERY STYLE DECIDES FROM WHAT IS ON THE STUDENT'S OWN SCREEN: their own cost, and
// the auction parameters the bidding screen prints (reserve, rival range, bidder count).
// NOTHING here reads a rival's cost, and nothing can — the server does not send one
// before the game ends (§4). A robot that was handed the rivals' draws would make the
// cohort's chart say something false about what a student can achieve.
//
// ⚠ `equilibrium` IS NOT A LEAK, for the same reason forecast's `regression-fitter` is
// not: β is a function of PUBLIC parameters (§5.1), all of which the bidding screen
// prints to every student. A student with the deck slide can compute it too. What would
// be a leak is a style that peeked at the realized rival bids, and none does.
// ═══════════════════════════════════════════════════════════════════════════════

/** β(c) — the reserve-conditioned equilibrium bid (§5.1), from PUBLIC parameters only.
 *
 *  ⚠ The second numerator term vanishes at the default reserve and this collapses to the
 *  simple form. It is kept because the reserve is instructor-adjustable: without it the
 *  `equilibrium` robot would drift OFF the optimal line at any other setting, and the
 *  cohort chart would quietly stop demonstrating the thing it exists to demonstrate. */
export function beta(c, { rivalCostMax, reserve, totalBidders: n }) {
  if (c > reserve) return null
  if (c >= rivalCostMax) return c
  const num = Math.pow(rivalCostMax - c, n) - Math.pow(rivalCostMax - reserve, n)
  const den = n * Math.pow(rivalCostMax - c, n - 1)
  return c + num / den
}

/** Every bid must be a whole number in [0, reserve] — the same gate validateBid applies
 *  server-side (§6.2). A style that returned something outside it would have its round
 *  refused, and the cohort would silently come up short. */
export const legal = (v, reserve) =>
  Math.max(0, Math.min(reserve, Math.round(Number.isFinite(v) ? v : 0)))

/** A small deterministic wobble, so a style is not a perfectly straight line on the
 *  chart. Keyed on the robot and the round, never on `Math.random`, so a dry run is
 *  reproducible and a failure can be re-run. */
const jitter = (key, spread) => {
  let h = 2166136261
  for (let i = 0; i < key.length; i++) { h ^= key.charCodeAt(i); h = Math.imul(h, 16777619) }
  return (((h >>> 0) % 1000) / 1000 - 0.5) * 2 * spread
}

export const STYLES = [
  {
    name: 'equilibrium',
    note: 'bids β exactly — the benchmark line, walking',
    bid: (cost, p) => legal(beta(cost, p) ?? 0, p.reserve),
  },
  {
    name: 'cost-bidder',
    note: 'bids its own cost — wins often, earns exactly nothing',
    bid: (cost, p) => legal(cost, p.reserve),
  },
  {
    name: 'over-marker',
    note: 'marks up roughly twice the optimum — rarely wins',
    bid: (cost, p) => {
      const b = beta(cost, p) ?? cost
      return legal(cost + (b - cost) * 2.2, p.reserve)
    },
  },
  {
    name: 'under-marker',
    note: 'shaves the optimum — wins more, earns thinner',
    bid: (cost, p) => {
      const b = beta(cost, p) ?? cost
      return legal(cost + (b - cost) * 0.45, p.reserve)
    },
  },
  {
    name: 'random-in-band',
    note: 'no policy — uniform between its cost and the reserve',
    bid: (cost, p, key) => legal(cost + Math.abs(jitter(key, 1)) * (p.reserve - cost), p.reserve),
  },
]

/** Round-robin, so every style is exercised at least once for any n ≥ STYLES.length. */
export function assignStyles(n) {
  return Array.from({ length: n }, (_, i) => STYLES[i % STYLES.length])
}
